# Generated by Django 5.0.6 on 2024-08-12 14:49

import chatbox.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_type', models.CharField(choices=[('MU', 'Mutual Chat'), ('GR', 'Group Chat')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('IM', 'Image'), ('VD', 'Video'), ('AD', 'Audio'), ('GN', 'Generic')], max_length=2)),
                ('file', models.FileField(upload_to=chatbox.models.FileData.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privileges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AM', 'Add Member'), ('KM', 'Kick Member'), ('DM', 'Delete Message'), ('GI', 'Change Group Info')], max_length=2), size=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('admins', models.ManyToManyField(related_name='+', through='chatbox.AdminRole', to=settings.AUTH_USER_MODEL)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_info', to='chatbox.chat')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adminrole',
            name='group_chat_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbox.groupchatinfo'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_message_id', models.CharField(default='0', max_length=20)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbox.chat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(through='chatbox.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20, unique=True)),
                ('sent_at', models.DateTimeField()),
                ('text', models.TextField(blank=True, max_length=5000, null=True, validators=[chatbox.models.string_not_empty])),
                ('service_action', models.CharField(blank=True, choices=[('CC', 'Create Chat')], max_length=2, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbox.chat')),
                ('file_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chatbox.filedata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(models.F('user_id'), models.F('chat_id'), name='membership_userid_chatid_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(models.F('message_id'), name='msg_msgid_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('chat_id', 'message_id'), name='msg_chatid_msgid_unique_idx'),
        ),
    ]
